/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intihotel;

import java.awt.HeadlessException;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author zayn
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        disc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPassport = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtPhone = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtDays = new javax.swing.JTextField();
        single = new javax.swing.JRadioButton();
        family = new javax.swing.JRadioButton();
        luxury = new javax.swing.JRadioButton();
        deluxe = new javax.swing.JRadioButton();
        bookingID = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel14.setText("Promo Code");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(360, 340, 90, 30);

        disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discActionPerformed(evt);
            }
        });
        getContentPane().add(disc);
        disc.setBounds(450, 340, 120, 28);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 150, 81, 36);

        jLabel2.setText("Passport");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 190, 92, 38);

        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(49, 290, 92, 43);

        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 220, 92, 61);

        jLabel5.setText("Date of Check in");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 160, 110, 16);

        jLabel6.setText("Number of Nights");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 200, 120, 16);

        jLabel7.setText("Room Type");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 250, 70, 16);

        jLabel8.setText("Booking ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 380, 69, 16);

        jButton1.setText("Back ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 440, 77, 29);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(150, 160, 143, 28);
        getContentPane().add(txtPassport);
        txtPassport.setBounds(150, 200, 151, 28);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(147, 298, 151, 84);
        getContentPane().add(txtPhone);
        txtPhone.setBounds(150, 240, 151, 28);
        getContentPane().add(txtDate);
        txtDate.setBounds(480, 160, 98, 28);
        getContentPane().add(txtDays);
        txtDays.setBounds(480, 200, 98, 28);

        buttonGroup1.add(single);
        single.setText("Single ");
        single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleActionPerformed(evt);
            }
        });
        getContentPane().add(single);
        single.setBounds(440, 250, 74, 23);

        buttonGroup1.add(family);
        family.setText("Famaliy ");
        family.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyActionPerformed(evt);
            }
        });
        getContentPane().add(family);
        family.setBounds(520, 250, 84, 23);

        buttonGroup1.add(luxury);
        luxury.setText("Luxury");
        luxury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luxuryActionPerformed(evt);
            }
        });
        getContentPane().add(luxury);
        luxury.setBounds(440, 290, 75, 23);

        buttonGroup1.add(deluxe);
        deluxe.setText("Deluex");
        getContentPane().add(deluxe);
        deluxe.setBounds(520, 290, 76, 23);
        getContentPane().add(bookingID);
        bookingID.setBounds(440, 380, 148, 25);

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 440, 82, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/logo.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 160, 220);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/Chcekin.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 20, 650, 110);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/whiteBG.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(153, -64, 580, 770);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/whiteBG.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 170, 180, 460);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/whiteBG.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(140, -4, 580, 130);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
     private void bttnActionPerformed(java.awt.event.ActionEvent evt) {                                         
     //setVisible(false);
        //new Bill().setVisible(true);  
        
        
     }
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
   


    }//GEN-LAST:event_txtNameActionPerformed

    private void familyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyActionPerformed

        
        

    }//GEN-LAST:event_familyActionPerformed

    private void singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleActionPerformed

        
    }//GEN-LAST:event_singleActionPerformed

    private void luxuryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luxuryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luxuryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     setVisible(false);
        new Menu().setVisible(true);    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

if (buttonGroup1.getSelection()==null)
          JOptionPane.showMessageDialog(null,"Please select a Room");
        else 
        try
        {
            
            File waitList = new File("/Users/adrianasyakirah/NetBeansProjects/RestTimeHotel/src/resttimehotel/WaitingList.txt");
            PrintWriter writer = new PrintWriter(waitList);
        String name = txtName.getText();
        writer.write(name);

        String passport = txtPassport.getText();
       

        String address = txtAddress.getText();
        
        
        String date = txtDate.getText();
        writer.write(date);
        
        String promoCode= disc.getText();
        

        int pNum = Integer.parseInt(txtPhone.getText());

        int numNights = Integer.parseInt(txtDays.getText());
         
        String room= "";
        int cost=0;

        if (single.isSelected()) {

            room = "Single Room";
            cost = 200;
            writer.write(room);
        }
        else if (family.isSelected()){
            room = "Family Room";
            cost = 450;
            writer.write(room);
        }

        else if (luxury.isSelected()){
            room = "Luxury Room";
            cost = 600;
            writer.write(room);
        }

        else if (deluxe.isSelected()){
            room = "Deluxe Room";
            cost = 800;
            writer.write(room);
        }
        Booking customer = new Booking ( name, passport, address, pNum, numNights, room, cost, promoCode, date);
        RestTimeHotel.bookDB[RestTimeHotel.i++] = customer;
        RestTimeHotel.bookingCount++;
        
        String x = Integer.toString(customer.getBookingID());
        bookingID.setText(x);
        
        writer.write(customer.getBookingID());
        
        String addMsg = "Your Booking was sent Successfully" 
                         + "\n Booking ID : " + customer.getBookingID();
        
                 
        JOptionPane.showMessageDialog(null,addMsg);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discActionPerformed

    
   

        
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton deluxe;
    private javax.swing.JTextField disc;
    private javax.swing.JRadioButton family;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton luxury;
    private javax.swing.JRadioButton single;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDays;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}



