/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intihotel;

/**
 *
 * @author osman
 */
public class RoomTypes extends javax.swing.JFrame {

    /**
     * Creates new form RoomTypes
     */
    public RoomTypes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deulxebtn = new javax.swing.JButton();
        signlebtn = new javax.swing.JButton();
        luxurybtn = new javax.swing.JButton();
        Backtomenu = new javax.swing.JButton();
        familybtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        deulxebtn.setText("View");
        deulxebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deulxebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deulxebtn);
        deulxebtn.setBounds(610, 460, 80, 29);

        signlebtn.setText("View");
        signlebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signlebtnActionPerformed(evt);
            }
        });
        getContentPane().add(signlebtn);
        signlebtn.setBounds(160, 280, 80, 29);

        luxurybtn.setText("View");
        luxurybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luxurybtnActionPerformed(evt);
            }
        });
        getContentPane().add(luxurybtn);
        luxurybtn.setBounds(170, 480, 90, 29);

        Backtomenu.setText("Back to Menu");
        Backtomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktomenuActionPerformed(evt);
            }
        });
        getContentPane().add(Backtomenu);
        Backtomenu.setBounds(300, 510, 170, 29);

        familybtn.setText("View");
        familybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familybtnActionPerformed(evt);
            }
        });
        getContentPane().add(familybtn);
        familybtn.setBounds(590, 280, 75, 29);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/DD.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(480, 350, 303, 137);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/LD.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 350, 350, 180);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/FD.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 180, 270, 130);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/SD.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 170, 310, 140);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Single Room");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 140, 120, 21);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/Rooms.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, -30, 378, 150);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Family Room");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 140, 105, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Luxury Room");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 320, 109, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Deluex Room");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 320, 104, 21);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/logo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 210, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/whiteBG.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 100, 561, 680);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/whiteBG.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-10, -10, 610, 750);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/whiteBG.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, -50, 530, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signlebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signlebtnActionPerformed
               setVisible(false); 
        new SingleRoom().setVisible(true);                                            

    }//GEN-LAST:event_signlebtnActionPerformed

    private void familybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familybtnActionPerformed
            setVisible(false); 
        new FamilyRoom().setVisible(true);


    }//GEN-LAST:event_familybtnActionPerformed

    private void luxurybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luxurybtnActionPerformed
         setVisible(false); 
        new LuxuryRoom().setVisible(true);
    }//GEN-LAST:event_luxurybtnActionPerformed

    private void deulxebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deulxebtnActionPerformed
         setVisible(false); 
        new DeluxeRoom().setVisible(true);
    }//GEN-LAST:event_deulxebtnActionPerformed

    private void BacktomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktomenuActionPerformed

       setVisible(false); 
        new Menu().setVisible(true);

    }//GEN-LAST:event_BacktomenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomTypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backtomenu;
    private javax.swing.JButton deulxebtn;
    private javax.swing.JButton familybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton luxurybtn;
    private javax.swing.JButton signlebtn;
    // End of variables declaration//GEN-END:variables
}
