/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intihotel;

import java.util.Date;

/**
 *
 * @author zayn
 */
public class Summary extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Summary() {
        initComponents();
    }
    public Summary(int Nights, int counter)
    {
            this();
           display(Nights, counter);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(300, 420, 75, 29);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(200, 420, 75, 29);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 130, 464, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 150, 190);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 170, 45, 16);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel7.setText("Summary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 60, 340, 43);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intihotel/whiteBG.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -140, 980, 830);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 60, 45, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     setVisible(false);
     new Menu().setVisible(true);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

    System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    
     
        
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Summary().setVisible(true);
            }
        });
    }
    
    public static int getRandomIntegerBetweenRange(int min, int max){
            int x = (int)(Math.random()*((max-min)+1))+min;
            return x;
        }
      public void display(int night, int counter)
    {
        Booking cust=RestTimeHotel.bookDB[counter];
        jTextArea1.setText("\t\tINTI Hotel");
        
        
  
        
        jTextArea1.setText("\n" + cust.getName() +" is assigned to room no. : " + getRandomIntegerBetweenRange(1, 99));
        
        
        jTextArea1.append("\n**************************************************************************\n");
        jTextArea1.append("\nCustomer Name: " + cust.getName());
        jTextArea1.append("\nPassport: " + cust.getPass());
        jTextArea1.append("\nDate of Check In: " + cust.getDate());
        jTextArea1.append("\nDate of Check Out: " + (new Date()));
        jTextArea1.append("\nPrice Per Night: " + cust.getCost());
        if(night>cust.getNumOfNights())
            
            
            jTextArea1.append("\n\n Fine per Night: 50 "
                              +"\nTotal of Fine : " + 50*(night-cust.getNumOfNights())
                              +"\nOutstanding: " + ((50*(night-cust.getNumOfNights())) + cust.getCost()*(night-cust.getNumOfNights())));

        
        else
            jTextArea1.append("\n\nFine: " + 0.00);
      

        jTextArea1.append("\n\nTotal Fees: " + cost(night,counter) );
        jTextArea1.append("\n**************************************************************************\n");

    }
      public int cost (int night, int counter){
          Booking cust = RestTimeHotel.bookDB[counter];
          int price = cust.getCost()*cust.getNumOfNights();
          if (night>cust.getNumOfNights()){
          price = (night * cust.getCost()) + 50*(night-cust.getNumOfNights());
      }
     if ("RestTimeHotel30".equalsIgnoreCase(cust.getPromoCode()))
         price = (price*30)/100;
     
     else if ("RTH50".equalsIgnoreCase(cust.getPromoCode())){
         price = (price*50)/100;
     }
     
     else if ("RTH20".equalsIgnoreCase(cust.getPromoCode())){
         price = (price*20)/100;
     }
     //else
          
          return price;
      }
      
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
